// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

// const inter = Inter({ subsets: ["latin"] });
import { Roboto_Mono, Work_Sans } from 'next/font/google'

const roboto_mono = Work_Sans({
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={roboto_mono.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
