export const portfolioProjects = [
  {
    slug: "heartwood-cabinetry",
    client: "Heartwood",
    title: "Cabinetry that quiets a room.",
    year: "2026",
    type: "Trades",
    status: "Live",
    summary: "A premium digital presence for custom cabinetry, showcasing craftsmanship through large imagery and refined typography.",
    services: ["Web Design", "Development"],
    outcome: "Built to reflect the precision and quality of their architectural woodwork.",
    palette: "bone",
    image: "/portfolio/heartwood.png",
    link: "https://tradeswebdemo1.vercel.app/",
  },
  {
    slug: "holm-real-estate",
    client: "HOLM",
    title: "An editorial listing experience for luxury real estate.",
    year: "2026",
    type: "Real Estate",
    status: "Live",
    summary: "A refined property showcase emphasizing imagery, space, and premium typography.",
    services: ["Web Design", "Platform"],
    outcome: "Designed to present luxury homes with the elegance they deserve.",
    palette: "graphite",
    image: "/portfolio/holm2.png",
    link: "https://realestatedemo1-konfxafqu-peterthecoder1234s-projects.vercel.app/",
  },
  {
    slug: "signal-desk",
    client: "Signal Desk",
    title: "A premium research platform for modern teams.",
    year: "2026",
    type: "Platform",
    status: "Live",
    summary: "Turn dense research into a premium product with cinematic media and data modules.",
    services: ["Web Design", "Development"],
    outcome: "Built to elevate research content into a cohesive, high-end experience.",
    palette: "moss",
    image: "/portfolio/signaldesk.png",
    link: "https://smallcapv2.vercel.app/",
  },
  {
    slug: "cascade-exteriors",
    client: "Cascade Exteriors",
    title: "A high-end digital presence for architectural exterior care.",
    year: "2026",
    type: "Trades",
    status: "Live",
    summary: "Built to endure. Finished to impress. A site reflecting the quality of their exterior services.",
    services: ["Website", "Branding"],
    outcome: "A stunning showcase of exterior care and outdoor lighting services.",
    palette: "bone",
    image: "/portfolio/cascade.png",
    link: "https://phcsite.vercel.app/",
  }
];
